{% set name = "surface-water-network" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/surface_water_network-{{ version }}.tar.gz
  sha256: da2d32efb578d58b11962cf6816ea6e15c756b0d2ddb5076ddd591e30bf6e720

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - geopandas >=0.9
    - matplotlib-base
    - packaging
    - pandas >=1.2
    - pyproj >=2.2
    - rtree
    - shapely

test:
  imports:
    - swn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwtoews/surface-water-network
  summary: Surface water network
  dev_url: https://github.com/mwtoews/surface-water-network
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwtoews
